swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: 1.0.0
  termsOfService: http://swagger.io/terms/
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            properties:
              email:
                type: string
                description: user email
              password:
                type: string
                description: user password
      produces:
        - application/json
      responses:
        "200":
          description: Login Successfully
          schema:
            type: object
            properties:
              token:
                type: string
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            properties:
              email:
                type: string
                description: user email
              password:
                type: string
                description: user password
              firstName:
                type: string
                description: user first name
              lastName:
                type: string
                description: user last name
              userName:
                type: string
                description: user public name
      produces:
        - application/json
      responses:
        "200":
          description: Signup Successfully
          schema:
            type: object
            properties:
              status:
                type: integer
              message:
                type: string
              body:
                type: object
                properties:
                  id:
                    type: string
                  email:
                    type: string
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            type: object
            properties:
              status:
                type: integer
              message:
                type: string
              body:
                type: object
                properties:
                  id:
                    type: string
                  email:
                    type: string
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            type: object
            properties:
              userName:
                type: string
      produces:
        - application/json
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            type: object
            properties:
              status:
                type: integer
              message:
                type: string
              body:
                type: object
                properties:
                  id:
                    type: string
                  email:
                    type: string
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/{accountId}/transactions:
    get:
      tags:
        - Transactions
      summary: Get all transactions
      security:
        - Bearer: []
      parameters:
        - in: path
          name: accountId
          description: Id of bank account
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: Successfully retrieval of transactions
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Transactions"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /transaction/{transactionId}:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions
      summary: Get transaction by id
      parameters:
        - in: path
          name: transactionId
          description: Id of the transaction
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: Return only transaction selected
          schema:
            $ref: "#/definitions/Transactions"
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Account not found
        "500":
          description: Unexpected Error
    put:
      security:
        - Bearer: []
      tags:
        - Transactions
      summary: Update Transaction information
      description: API to update transactions
      parameters:
        - in: path
          name: transactionId
          required: true
          type: string
          description: Unique id to update the transactions
        - in: body
          name: Body
          required: true
          schema:
            $ref: "#/definitions/UpdateTransaction"
      responses:
        "200":
          description: Transaction category updated successfully.
        "400":
          description: Invalid transaction category data.
        "401":
          description: Unauthorized.
        "404":
          description: Transaction not found.
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  UpdateTransaction:
    properties:
      category:
        type: string
        description: transaction category name
      note:
        type: string
        description: transaction note
  Transactions:
    properties:
      date:
        type: string
        description: Transaction date
      description:
        type: string
        description: Transaction description
      amount:
        type: string
        description: Transaction amount
      balance:
        type: string
        description: Balance transaction
      type:
        type: string
        description: Transaction type
      category:
        type: string
        description: transaction category
      note:
        type: string
        description: Note about the transaction
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string
